# Generated by Django 5.2 on 2026-08-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('ESCALERILLA', 'Escalerilla'), ('ELIMINACION_DIRECTA', 'Eliminación directa')], default='PENDIENTE', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABIERTA', 'Abierta'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('registration_deadline', models.DateField()),
            ],
        ),
    ]
