# Generated by Django 5.2 on 2026-08-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABIERTA', 'Abierta'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('ESCALERILLA', 'Escalerilla'), ('ELIMINACION_DIRECTA', 'Eliminación directa')], max_length=30),
        ),
    ]
