# Generated by Django 5.2 on 2026-08-14 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.PositiveIntegerField()),
                ('minimum_players', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_categories', to='core.category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_categories', to='core.competition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competition', 'category'), name='unique_competition_category')],
            },
        ),
    ]
