# Generated by Django 5.2 on 2026-08-14 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_competitioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.competitioncategory')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'competition_category'), name='unique_player_competition_category')],
            },
        ),
    ]
