# Generated by Django 5.2 on 2026-08-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='core.category'),
        ),
    ]
