# Generated by Django 5.2 on 2026-08-14 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_player_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='core.category'),
        ),
    ]
