# Generated by Django 5.2 on 2026-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_player_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Ocupada'), ('MAINTENANCE', 'Mantención')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
