# Generated by Django 5.2 on 2026-08-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_court'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('round', models.PositiveIntegerField(blank=True, null=True)),
                ('is_walkover', models.BooleanField(default=False)),
                ('competition_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.competitioncategory')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='core.court')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1', to='core.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player2', to='core.player')),
                ('winner_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to='core.player')),
            ],
        ),
    ]
