# Generated by Django 5.2 on 2026-08-14 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('games_player1', models.PositiveIntegerField()),
                ('games_player2', models.PositiveIntegerField()),
                ('is_super_tie_break', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.match')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'set_number'), name='unique_match_set_number')],
            },
        ),
    ]
