# Generated by Django 5.2 on 2026-08-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_matchset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('walkovers_won', models.PositiveIntegerField(default=0)),
                ('walkovers_lost', models.PositiveIntegerField(default=0)),
                ('sets_won', models.PositiveIntegerField(default=0)),
                ('sets_lost', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.competitioncategory')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competition_category', 'player'), name='unique_standing_player_competition_category')],
            },
        ),
    ]
