# Generated by Django 5.2 on 2026-08-28 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['competition_category', 'round', 'bracket_position', 'id']},
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_matches', to='core.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match_slot',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Jugador 1'), (2, 'Jugador 2')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1', to='core.player'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('competition_category', 'round', 'bracket_position'), name='unique_match_bracket_position'),
        ),
    ]
