# Generated by Django 5.2 on 2026-08-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_match_options_match_bracket_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match_bracket_position',
        ),
        migrations.AddField(
            model_name='match',
            name='resolution_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WALKOVER', 'Walkover'), ('RETIREMENT', 'Retiro')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='core.match'),
        ),
    ]
