# Generated by Django 5.2 on 2026-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchset',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
